### ISSUE TITLE
[Bug report] @temp returns an empty object by import.meta.glob

### ISSUE THREAD

**Issue by Hooper93** [vuepress/core#1226]
### Description

我正在使用 vuepress-next 开发一个主题，版本是： "2.0.0-beta.60",
I am developing a theme using vuepress-next. The version is: "2.0.0-beta. 60",

我遇到一个问题：就是我的主题通过 vuepress-plugin-use-pages 在 vite server 启动前，在 .temp 目录生成了一些临时文件
I ran into a problem: my blog theme generated some temporary files in the .temp directory before the vite server was started through vuepress-plugin-use-pages

<img width="129" alt="image" src="https://user-images.githubusercontent.com/48215196/210940810-f91416d1-90cf-4186-89de-a5fd7c0ec161.png">

但是我通过 `import.meta.glob('@temp/*.js')` 得到的是一个空对象，而通过 ` import.meta.glob('../../vuepress/.temp/*.js') ` 却可以得到正确的文件列表：
However, I get an empty object through `import.meta.glob('@temp/*. js') `, while I get the correct file list through ` import. meta.glob('../../vueporess/.temp/*. js')`:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/48215196/210941342-7aa102f0-8bec-4af6-816a-0b877df4933d.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/48215196/210941398-b9ca213b-ee49-496a-8b8f-5983825927cc.png">

感觉像是 alias 的问题？请修复它。
It feels like the problem of Alias? Please fix it.

### Reproduction

nothing

### Used Package Manager

npm

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) x64 Apple M1
    Memory: 250.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  Browsers:
    Chrome: 108.0.5359.124
    Edge: Not Found
    Firefox: 78.7.1
    Safari: 16.1
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli: Not Found
    @vuepress/client: 2.0.0-beta.60 => 2.0.0-beta.60 
    @vuepress/core: Not Found
    @vuepress/markdown: Not Found
    @vuepress/plugin-active-header-links: Not Found
    @vuepress/plugin-back-to-top: Not Found
    @vuepress/plugin-container: 2.0.0-beta.60 => 2.0.0-beta.60 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon: 2.0.0-beta.60 => 2.0.0-beta.60 
    @vuepress/plugin-git: Not Found
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom: Not Found
    @vuepress/plugin-nprogress: Not Found
    @vuepress/plugin-palette: Not Found
    @vuepress/plugin-prismjs: Not Found
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data: 2.0.0-beta.60 => 2.0.0-beta.60 
    @vuepress/plugin-toc: 2.0.0-beta.60 => 2.0.0-beta.60 
    @vuepress/shared: Not Found
    @vuepress/theme-default: Not Found
    @vuepress/utils: 2.0.0-beta.60 => 2.0.0-beta.60 
    vue: ^3.2.45 => 3.2.45 
    vue-loader: Not Found
    vue-router: Not Found
    vuepress: 2.0.0-beta.60 => 2.0.0-beta.60 
    vuepress-vite: Not Found
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
HI, some updates here, can you check if alias works for this in a normal vite app? If not please open an issue to vite.

**Comment by Hooper93** [comment]
I tried again, but the problem still exists. The npm package I used is as follows：
"vuepress": "^2.0.0-beta.61",（latest）
"vite": "^4.2.1",（latest）

I don’t think I should go to the Vite official website to raise an issue,  because the @temp feature is provided by vuepress-next, not Vite’s API itself.
see: https://v2.vuepress.vuejs.org/advanced/cookbook/passing-data-to-client-code.html#write-and-load-temp-files

**Comment by Mister-Hope** [comment]
> can you check if alias works for this in a normal vite app

Are you sure you understand my questions correctly? I am asking if `import.meta.glob` (it's provided by vite) support alias or not, as `@temp` is just a normal alias injected by vuepress.

**Comment by meteorlxy** [comment]
Closing as no activities for a long time
