### ISSUE TITLE
Add title support for code blocks

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/core#1277]
### Clear and concise description of the problem

It would be great if people can set a file name for code blocks, e.g.
````md
```js [.vuepress/config.js] {1,3}
const a = 1;

console.log(“hello world”)
```
````

### Suggested solution

Above

**Comment by nimonian** [comment]
Seconded, I would love this too. Perhaps, when the title is provided, it could replace the language name that appears in the top right?

**Comment by Mister-Hope** [comment]
PR welcomed for this. It would be great if you could help.

**Comment by nruffing** [comment]
I can help with this if you would like to assign this to me.  I like the the idea of of being able to specify text to override the displayed language name, especially for setting it to a filename.
