### ISSUE TITLE
[Feature request] Code Import single lines

### ISSUE THREAD

**Issue by vordimous** [vuepress/core#1355]
### Clear and concise description of the problem

Allow the same code line selection for imports as for highlighting. This will make adding instructions from runnable files easier since there may be many different lines in a bash script, for instance, that are needed to run a test but not needed to be displayed to the user.

Will render: `@[code{1-1}](../foo.js)`
Doesn't render: `@[code{1}](../foo.js)`
Doesn't render: `@[code{2,4}](../foo.js)`

### Suggested solution

You could add the same code line selection for highlighting lines as for imported code blocks.

**Comment by Mister-Hope** [comment]
I don't think the first case is needed, why do you need to import one single line from other files instead of direct writing that?
 Also I don't think importing pieces and merging them is a common feature.

You can use inclide feature with `vuepress-plguin-md-enhance` inside code blocks as a workaround

**Comment by vordimous** [comment]
@Mister-Hope The use case for single-line import is that we have many different short samples to display to the user. We have them defined in runnable scripts where we display individual steps for the user to follow. This way, the code we test and the code the user uses are the same. Many of those steps are just one line of code. 

Please consider at least single line imports if possible.

**Comment by Mister-Hope** [comment]
Tbh, the first one does have workaround, didn't it?

Anyway contribution welcome, I don't think any disadvantages to support it.

**Comment by vordimous** [comment]
yes you can use a range that has the same line number `@[code{11-11}](.)`. This isn't a blocking issue that I can think of.

**Comment by Mister-Hope** [comment]
We are closing this as we support `1-` and `-5` (meaning "1 to end" and "1-5") `3-` and `3` may confuse the user.

**Comment by Mister-Hope** [comment]
Oh wait, I read again your original request, it seems you want something like:

`@[code{2,4-5,6}](../foo.js)`

Code region is better than setting with lines, as the file content may change through time, you can use it with https://plugin-md-enhance.vuejs.press/guide/include.html.

The include plugin has highest priority (even before code blocks), so you can probably use:

````md
```js
<!-- @include: ./foo.js{1} -->
<!-- @include: ./foo.js{2-4} -->
<!-- @include: ./foo.js#part1 -->
```
````

**Comment by Mister-Hope** [comment]
I do not think we need to support `@[code{2,4-5,6}](../foo.js)`, waiting for @meteorlxy opinion before finally closing this issue

**Comment by vordimous** [comment]
Thank you @Mister-Hope, I like the @include option since it allows for code highlighting separate from the import and the snippet feature is nice. 

I did not find the individual line support you mention to work:
```js
<!-- @include: ./foo.js{1} -->
<!-- @include: ./foo.js{2-4} -->
<!-- @include: ./foo.js#part1 -->
```
![image](https://github.com/vuepress/vuepress-next/assets/3012311/540c6b2d-5249-4752-9fc6-8d76a3c1a024)

```
    "vue": "^3.3.4",
    "vuepress": "2.0.0-beta.67",
    "vuepress-theme-hope": "2.0.0-beta.238"
```

**Comment by Mister-Hope** [comment]
> I do not think we need to support `@[code{2,4-5,6}](../foo.js)`, waiting for @meteorlxy opinion before finally closing this issue

CC @meteorlxy

**Comment by Mister-Hope** [comment]
> Thank you @Mister-Hope, I like the @include option since it allows for code highlighting separate from the import and the snippet feature is nice.
> 
> I did not find the individual line support you mention to work:
> 
> ```js
> 
> 
> 
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/3012311/274359789-540c6b2d-5249-4752-9fc6-8d76a3c1a024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzg4ODYsIm5iZiI6MTcwNjA3ODU4NiwicGF0aCI6Ii8zMDEyMzExLzI3NDM1OTc4OS01NDBjNmIyZC01MjQ5LTQ3NTItOWZjNi04ZDc2YTNjMWEwMjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMDY0MzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM4MzJhNjc2NzgxZmUxZmNlNWRiY2I5MTU4OGVjNjBmNjdkN2Q4ZTMwYWQxMTdjYTY2NjAxNTRmYzFjMTE2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6xzOdPkTsX_yekOxT8SLrf_am6EX_BgKT1yNs21z26s)
> 
> ```
>     "vue": "^3.3.4",
>     "vuepress": "2.0.0-beta.67",
>     "vuepress-theme-hope": "2.0.0-beta.238"
> ```

You can report issues in vuepress-theme-hope repo.

**Comment by vordimous** [comment]
> You can report issues in vuepress-theme-hope repo.

I created a ticket to track @include here: https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3855
