### ISSUE TITLE
There is no index.html file after packaging

### ISSUE THREAD

**Issue by W-HanYu** [vuepress/core#1462]
### Description

<img width="335" alt="截屏2024-01-07 00 00 51" src="https://github.com/vuepress/core/assets/91104567/22d644d9-9f06-41ff-80e2-a66204a929b6">

### Reproduction

无

### Used Package Manager

yarn

### System Info

```shell
vuepress build docs
```

**Comment by Mister-Hope** [comment]
Why there should be a homepage while you are not providing one:

![image](https://github.com/vuepress/core/assets/33315834/28043894-5258-4dad-a545-591fc1b0e386)
