### ISSUE TITLE
[Feature request] 打包后的细碎的 js 文件太多了，每次加载的时候，加载几百个js文件，能合并成一个js吗？

### ISSUE THREAD

**Issue by geeeeeeeek** [vuepress/core#1463]
### Clear and concise description of the problem

打包后的细碎的 js 文件太多了，每次加载的时候，加载几百个js文件，能合并成一个js吗？ 比如我的[个人博客](https://gitapp.cn) 每次加载的时候，从F12控制台可以看出，需要加载很多js小文件。 

so many js files. how can I merge them?

![abc](https://github.com/vuepress/core/assets/5697564/591e6dae-d4de-43f6-8645-87005618bcf2)

### Suggested solution

希望能通过配置，合并js文件

**Comment by Mister-Hope** [comment]
cc @meteorlxy I think I reported before, if `usePagesData` is never used, then we can merge page component and page data of 1 single page into 1 single chunk.

**Comment by meteorlxy** [comment]
You can turn off [shouldPreload](https://v2.vuepress.vuejs.org/reference/config.html#shouldpreload) or [shouldPrefetch](https://v2.vuepress.vuejs.org/reference/config.html#shouldprefetch).
