### ISSUE TITLE
"deploy": "vuepress build ."

### ISSUE THREAD

**Issue by W-HanYu** [vuepress/core#1474]
### Description

使用此命令时，报错：
<img width="651" alt="image" src="https://github.com/vuepress/core/assets/91104567/5aa3d44a-82ca-41ae-964e-afd8c5d9a370">
<img width="935" alt="image" src="https://github.com/vuepress/core/assets/91104567/2ae9a65d-0639-47cb-b0e6-edc32943d17f">

项目目录
<img width="370" alt="image" src="https://github.com/vuepress/core/assets/91104567/c524bddd-6d66-4dd3-a8ec-cc2841b34066">

### Reproduction

无

### Used Package Manager

yarn

### System Info

```shell
<img width="651" alt="image" src="https://github.com/vuepress/core/assets/91104567/5aa3d44a-82ca-41ae-964e-afd8c5d9a370">
<img width="935" alt="image" src="https://github.com/vuepress/core/assets/91104567/2ae9a65d-0639-47cb-b0e6-edc32943d17f">
```

**Comment by W-HanYu** [comment]
https://github.com/W-HanYu/FE-JS-TS 这是我的仓库地址，可以拉下来deploy试一下哈

**Comment by Mister-Hope** [comment]
That is absolutely not a minimal reproduction. You'd better check if some of your page has a invalid date field in frontmatter 

We don't want pay our time at your own business.

Provide a **minimal** reproduction.
