### ISSUE TITLE
[Bug report] resolveRoute does not support relative path

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/core#1492]
### Description

`resolveRoute` should support relative path, just like `router.resolve()`

E.g.:

```ts
// at /page/a.html
resolve('b.html') // should be /page/b.html
resolve('../') // should be /
```

## Why this is needed

prev and next links are based on current route path, as people just set relative links like `./a.md` and `../`

**Comment by meteorlxy** [comment]
Closed by #1545
