### ISSUE TITLE
[Bug report] defineClientConfig is still broken under pnpm

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/core#1495]
### Description

See ecosystem, when removing the `as ClientConfig` and type import, type errors are still seen

![image](https://github.com/vuepress/core/assets/33315834/2a63b4f4-4e9f-465a-bca5-bfc17062f887)

### Reproduction

https://github.com/vuepress/ecosystem

### Used Package Manager

pnpm

### System Info

```shell
.
```

**Comment by meteorlxy** [comment]
Per https://github.com/microsoft/TypeScript/issues/42873#issuecomment-2065572017, it would be fixed in TS 5.5. Let's wait for the new release then.

**Comment by meteorlxy** [comment]
Should have been solved since [TS 5.5](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/)
