### ISSUE TITLE
[Bug report] getters-should-be-side-effect-free

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/core#1500]
### Description

app.js:283 [Vue warn] Computed is still dirty after getter evaluation, likely because a computed is mutating its own dependency in its getter. State mutations in computed getters should be avoided.  Check the docs for more details: https://vuejs.org/guide/essentials/computed.html#getters-should-be-side-effect-free

### Reproduction

1. Checkout to branch `computed` (it has latest deps)
1. Install deps
1. Run e2e docs

![image](https://github.com/vuepress/core/assets/33315834/60456c7c-11dc-45d5-a6a9-628953494ed4)

**Comment by meteorlxy** [comment]
See https://github.com/vueuse/vueuse/issues/3794
