### ISSUE TITLE
[Bug report] Replace webpack-chain with webpack-5-chain

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/core#1503]
### Description

Technically speaking, webpack-chain never adds support for webpack v5, and the latest version was published 4 years ago

The maintainer already deprecates the package, so we'd better drop it.

See https://www.npmjs.com/package/webpack-chain

**Comment by meteorlxy** [comment]
Any suggested alternatives?

**Comment by Mister-Hope** [comment]
https://www.npmjs.com/package/webpack-5-chain


I think this package is widely used, and I would prefer changing to this one.
