### ISSUE TITLE
[Bug report] 以文件路径作为超链接，且该文件定义了`permalink`时，路由解析跳转到 404

### ISSUE THREAD

**Issue by pengzhanbo** [vuepress/core#1516]
### Description

当 md 文件名中包含 中文时，且 该文件定义了 `frontmatter.permalink` ，
如果使用了 `[xxx](./测试1.md)` 用文件名作为跳转链接，将会跳转到 404。

初步排查是由于 文件路径编码引发。
[/core/src/app/prepare/prepareRoutes.ts](https://github.com/vuepress/core/blob/main/packages/core/src/app/prepare/prepareRoutes.ts#L68) ，在生成 `redirects` 时，`redirect` 使用的是 未编码的 文件路径。
而在 linksPlugin 中，生成 链接路径的 [`resolvePaths`](https://github.com/vuepress/core/blob/main/packages/markdown/src/plugins/linksPlugin/resolvePaths.ts#L40) 函数中会对 文件路径进行 编码。
导致在 client 端中的 [`resolveRoutePath`](https://github.com/vuepress/core/blob/main/packages/client/src/router/resolveRoutePath.ts) 函数 未查找到 重定向地址。
在 [router.beforeResolve](https://github.com/vuepress/core/blob/main/packages/client/src/router/createVueRouter.ts#L43) 钩子跳转到了 404 。

### Reproduction

https://stackblitz.com/edit/vuepress-svx1ub?file=docs%2FREADME.md

### Used Package Manager

pnpm

### System Info

```shell
System:
    OS: macOS 14.2.1
  Binaries:
    Node: 21.3.0 
    Yarn: 1.22.19 
    npm: 10.2.4 
    pnpm: 8.15.4 
    bun: Not Found
  Browsers:
    Chrome: 122.0.6261.129
    Edge: Not Found
    Safari: 17.2.1
  npmPackages:
    @vuepress/bundler-vite: 2.0.0-rc.8 => 2.0.0-rc.8 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli: Not Found
    @vuepress/client: Not Found
    @vuepress/core: Not Found
    @vuepress/markdown: Not Found
    @vuepress/shared: Not Found
    @vuepress/utils: Not Found
    vue: ^3.4.21 => 3.4.21 
    vue-router: Not Found
    vuepress: ^2.0.0-rc.8 => 2.0.0-rc.8
```

**Comment by meteorlxy** [comment]
<img width="675" alt="image" src="https://github.com/vuepress/core/assets/18205362/34d705a9-96f8-41cf-b32b-2118df91fd00">

这个应该是正常访问吧？

**Comment by pengzhanbo** [comment]
> <img alt="image" width="675" src="https://private-user-images.githubusercontent.com/18205362/314361388-34d705a9-96f8-41cf-b32b-2118df91fd00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDI1NDksIm5iZiI6MTcxMDkwMjI0OSwicGF0aCI6Ii8xODIwNTM2Mi8zMTQzNjEzODgtMzRkNzA1YTktOTZmOC00MWNmLWIzMmItMjExOGRmOTFmZDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAyMzcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZDNiYjU3NDFjOTA2MmM5Y2JhOWNmNmM1ZjNlYjI3YmMzNjI1NWMwYTY1MzEzNWQyNDU2MWJkNzNiMzJhODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r5gE3W_fCMLPxF4EYdyJZLEv1xlAy3tDTH3tcrX0e8I">
> 这个应该是正常访问吧？

是的，可以访问，我标记错了。
