### ISSUE TITLE
[Bug report] mailto: and tel: are no longer supported

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/core#1528]
### Description

They don't have standard protocols like `abc://`.

We might need a full list of these protocols.

**Comment by lancy6001** [comment]
Thank you, once really resolved this issue of "mailto: and tel: are no longer supported" , please let me know. Many Thanks.

**Comment by Mister-Hope** [comment]
> We might need a full list of these protocols.

I still got no idea about this

**Comment by lll4770** [comment]
> > We might need a full list of these protocols.
> 
> I still got no idea about this

I don't know it either, but for the email standard protocol, I think it should start with "mailto:".

**Comment by lll4770** [comment]
// vite.config.js

export default {
  optimizeDeps: {
    exclude: ['mailto:']
  }
}

FYI. This result came from ChatGPT, but it didn't work for me.

**Comment by lancy6001** [comment]
But before upstream/upgrade, the maito:xxx@xxx.com is worked, after upgrade, the behavior is no longer worked.

**Comment by Mister-Hope** [comment]
The fix is applied here https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/4044
