### ISSUE TITLE
[Bug report] Duplicate webpack chunkname with different pages

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/core#1531]
### Description

The `resolvePageChunkInfo` use `sanitizeFileName` on `basename`, but in this case, the following pages chunk name will be the same:

- /a/name.html
- /b/name.html

@meteorlxy Could you please explain what you are doing at https://github.com/vuepress/core/commit/4f89d3915818a96e8afee61fbb1245120a231686

**Comment by meteorlxy** [comment]
Ah, that commit was to make the webpack chunk name more consistent with vite. Should add hash after them.
