### ISSUE TITLE
[Bug report] When the page path includes `hash`/ `query`, the page will load a 404 error.

### ISSUE THREAD

**Issue by pengzhanbo** [vuepress/core#1561]
### Description

After upgrading from `rc.9` to `rc.11`, there was a change in `beforeResolve` where the path comparison switched from `to.path` to `to.fullpath`. 

However, `to.fullpath` includes the `hash` portion, which causes issues when the page is first loaded or when navigating to a page with a `hash` in the path, resulting in the inability to match the correct route and leading to a `404` error.

<img width="1410" alt="image" src="https://github.com/vuepress/core/assets/16745751/727e0427-b191-4b03-bf05-3e56076283f1">

### Reproduction

-

### Used Package Manager

pnpm

### System Info

```shell
vuepress: 2.0.0-rc.11 => 2.0.0-rc.11
```

**Comment by digital-codes** [comment]
Just discovered a probably related bug. Using url query parameters like ?id=1 leads to a 404 as well. 
Install a fresh vuepress with cli and npm. Error occurs with any query string

**Comment by pengzhanbo** [comment]
> Just discovered a probably related bug. Using url query parameters like ?id=1 leads to a 404 as well. Install a fresh vuepress with cli and npm. Error occurs with any query string
> 
> Previous versions worked like so: [vp2.akugel.de/news.html?id=1](https://vp2.akugel.de/news.html?id=1) Now is broken

I have also noticed this issue, and I will fix it together in the PR #1562 .
