### ISSUE TITLE
[Bug report] vite 5.2.12 failed to build dynamic imported style files

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/core#1573]
### Description

When building with vite 5.2.12, vuepress failed to externalize style imports like `css` or `scss` while preforming SSG

### Reproduction

This is confirmed in our ecosystem and we are using `pnpm.overrides` to downgrade to `5.2.11`

### Used Package Manager

pnpm

### Workaround for anyone

Use vite 5.2.11

**Comment by meteorlxy** [comment]
Could you provide a reproduction based on our e2e? I could not reproduce it by [19e4d40](https://github.com/vuepress/core/commit/19e4d4054154051475ceccf9bb333bf5aefde0c4)

**Comment by Mister-Hope** [comment]
> Could you provide a reproduction based on our e2e? I could not reproduce it by [19e4d40](https://github.com/vuepress/core/commit/19e4d4054154051475ceccf9bb333bf5aefde0c4)

The file should from a package, and it's imported using `import()`

```js
import('@docsearch/css')
// or
import('@waline/client/waline-meta.css')
```

This is likely to be a Vite bug.

**Comment by meteorlxy** [comment]
Reproduced with e2e case.

**Comment by meteorlxy** [comment]
@Mister-Hope - I think you'd better limit the vite version to `<5.2.12` for the related plugins.

**Comment by meteorlxy** [comment]
https://github.com/vitejs/vite/issues/17366
