### ISSUE TITLE
[Bug report]  Cannot find package '@internal/routes'

### ISSUE THREAD

**Issue by arranf** [vuepress/core#1587]
### Description

Build fails with Error

`[ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/routes' imported from /Users/arran/projects/arranf.github.io/node_modules/@vuepress/client/dist/chunk-YRXAAVF4.js`

I've tried:
* Pinning the Vite version
* Using rc13

This appears to be an issue with either `tsup` or `@vuepress/bundler-vite`

Another user seems to have had this problem: https://github.com/vuepress/core/discussions/1572

### Reproduction

https://github.com/arranf/arranf.github.io/

### Used Package Manager

yarn

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 350.02 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: Not Found
    bun: Not Found
  Utilities:
    Git: 2.39.3 - /usr/bin/git
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Not Found
    Safari: 17.5
  npmPackages:
    @vuepress/bundler-vite: ^2.0.0-rc.14 => 2.0.0-rc.14
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-rc.14
    @vuepress/client:  2.0.0-rc.14
    @vuepress/core:  2.0.0-rc.14
    @vuepress/markdown:  2.0.0-rc.14
    @vuepress/shared:  2.0.0-rc.14
    @vuepress/utils:  2.0.0-rc.14
    vue:  3.4.31
    vue-router:  4.4.0
    vuepress: ^2.0.0-rc.14 => 2.0.0-rc.14
```

**Comment by Mister-Hope** [comment]
You are making too many customizations in your repo. Remove all of them and consider providing a minimal reproduction.
