### ISSUE TITLE
[Feature request] 右侧锚点侧边栏不知道要怎么才能显示

### ISSUE THREAD

**Issue by sunnysteam** [vuepress/core#1596]
### Clear and concise description of the problem

使用的默认主题
已经试过几个官方插件了，但是都不管用了，是不是已经不支持了

### Suggested solution

希望能够增加右侧侧边栏，专门显示文档内部的结构

**Comment by Mister-Hope** [comment]
The default theme does not support this, but the new one will, check the working draft at ecosystem repo which is made by @pengzhanbo https://github.com/vuepress/ecosystem/pull/134

Third party theme support this, like https://theme-hope.vuejs.press/, https://theme-plume.vuejs.press/ and  https://theme-reco.vuejs.press/
