### ISSUE TITLE
[Bug report] vuepress dev docs 启动项目时，报错

### ISSUE THREAD

**Issue by hmyjyghh** [vuepress/core#1604]
### Description

用 vuepress dev docs 命令 启动项目时，报错：SyntaxError: The requested module 'node:events' does not provide an export named 'addAbortListener'
![image](https://github.com/user-attachments/assets/e0642869-053b-4119-b303-f65ffe9c64ce)

我看vuepress 官网说需要node环境： [Node.js v18.16.0+]  我用 v18.17.0   也会报错

![image](https://github.com/user-attachments/assets/7dd866d9-8aa9-4fae-bb14-5e31d9a41526)
后用了 node 环境： v20.17.0 版本才可以

注意：如果npm 版本过低，比如： 
![img_v3_02e7_4c8373ec-d9be-4e89-ae47-4d2021c5f9dg](https://github.com/user-attachments/assets/da34ff56-1b4f-42f6-a9ec-f4e6e55cd738)

后来使用：  npm install -g npm@latest   升级了 npm 版本，目前npm 版本为：npm@10.8.3

声明：我之前安装node.js 的时候，版本比较老，所以自带的npm 版本也比较老，后面我切换 和 安装 node  都是使用的 gnvm， 所以未升级过  npm  版本

### Reproduction

123

### Used Package Manager

npm

### System Info

```shell
{
  "name": "new-blog",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "vuepress dev docs",
    "build": "vuepress build docs",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@vuepress/bundler-vite": "^2.0.0-rc.15",
    "@vuepress/theme-default": "^2.0.0-rc.42",
    "vuepress": "^2.0.0-rc.15"
  }
}
```

**Comment by meteorlxy** [comment]
Thanks for reporting. One of our dependencies execa has started to require node v18.19.0+. Will update the docs.
