### ISSUE TITLE
[Feature request] Link check support

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/core#945]
## Clear and concise description of the problem

If we can add ability to check markdown links in devServer and warn users about broken link, we can improve user experience.

## Suggested solution

Provide a link check option

![image](https://user-images.githubusercontent.com/33315834/173734641-aeb23fab-2394-44cc-bf97-1c5599a65df5.png)

### Use [`vuepress-plugin-md-enhance`](https://plugin-md-enhance.vuejs.press) It supports this out-of-box

**Comment by meteorlxy** [comment]
Could be a plugin

**Comment by Mister-Hope** [comment]
`vuepress-plugin-md-enhance` already support this (and also GFM, so I would like your suggestions about converting it to an official plugin)

**Comment by Mister-Hope** [comment]
I think it's time for us to review this again.

https://vuepress-theme-hope.github.io/v2/md-enhance/guide/others.html#link-check supports it every well. Shall I open a PR to move it to `@vuepress/markdown` or remain this feature in my plugin?

@meteorlxy

**Comment by Mister-Hope** [comment]
An official plugin is released.
